### ISSUE TITLE
Lightening Version Enhancement: Add Tensorboard monitoring and train from resume functions

### ISSUE THREAD

**Issue by yyyujintang** [chengtan9907/OpenSTL#105]
# 1.Add Tensorboard monitoring function
In openstl/api/exp.py:
**from pytorch_lightning.loggers import TensorBoardLogger**
In BaseExperiment Class:
def _init_trainer(self, args, callbacks, strategy):
    **logger = TensorBoardLogger("tb_logs", name=self.args.ex_name) # define logger here**
    trainer_config = {
        'devices': args.gpus,  # Use the all GPUs
        'max_epochs': args.epoch,  # Maximum number of epochs to train for
        "strategy": strategy, # 'ddp', 'deepspeed_stage_2', 'ddp_find_unused_parameters_false'
        'accelerator': 'gpu',  # Use distributed data parallel
        'callbacks': callbacks,
        **'logger': logger,  # Add the TensorBoard logger here
        'resume_from_checkpoint': args.ckpt_path if args.ckpt_path else None,  # train from resume**
    }
    return Trainer.from_argparse_args(argparse.Namespace(**trainer_config))
# 2.Add train from resume function
In addition to code in 1.
In openstl/utils/parser.py:
**parser.add_argument('--ckpt_path', type=str)**

**Comment by chengtan9907** [comment]
Thank you for your kind contribution. I added `ckpt_path` in the [commit](https://github.com/chengtan9907/OpenSTL/commit/314e8b4f827a8de844c80823e5a75b67f285db99).

I did not add the tensorboard logger because it seems less necessary for most users.  Also, someone may prefer wandb logger.  I leave this for users to add by themselves.
