### ISSUE TITLE
Find difference between the results of OpenSTL and the original paper?

### ISSUE THREAD

**Issue by Leiyi-Hu** [chengtan9907/OpenSTL#30]
Thanks for the great work! But I am confused by the results reported in your OpenSTL paper, it seems that the results are different from the results in the original papers. For example, the result of MovingMNIST in SimVP(original paper) is 23.8 (MSE), but in this repo the result is 32.15 (MSE).  And there are a lot of the same problems for other methods, such as PredRNN++.  So could you explain this? Are the results reproduced by the OpenSTL framework just not the same as the original ones? or there are some other reasons? Thanks in advance！

Best

**Comment by chengtan9907** [comment]
Hi, thank you for your interest in our work! 

The experimental results in OpenSTL differ from SimVP primarily due to different experimental settings, particularly in terms of the number of training epochs. OpenSTL reports results based on training for 200 epochs, whereas the original SimVP paper reports results based on training for 2000 epochs.

**Comment by chengtan9907** [comment]
The results in the original SimVP paper were copied from each individual paper, while OpenSTL reran various algorithms using a unified framework and consistent protocol.

**Comment by Leiyi-Hu** [comment]
> 
I get it! Thanks!
