### ISSUE TITLE
update_config function makes it unable to adjust learning rate by config

### ISSUE THREAD

**Issue by Pachark** [chengtan9907/OpenSTL#42]
In utils/main_utils/update_config, it seems the config will be replaced by default args. So when I changed the learning rate in config, it may print 'overwrite config key -- lr: 0.005 -> 0.001'. And the actual learning rate is always 0.001

What's the purpose of update_config function?

`def update_config(args, config, exclude_keys=list()):
    """update the args dict with a new config"""
    assert isinstance(args, dict) and isinstance(config, dict)
    for k in config.keys():
        if args.get(k, False):
            if args[k] != config[k] and k not in exclude_keys:
                print(f'overwrite config key -- {k}: {config[k]} -> {args[k]}')
            else:
                args[k] = config[k]
        else:
            args[k] = config[k]
    print(args)
    return args`

**Comment by mauriciodev** [comment]
I think the problem persists on the master branch. I wrote a pull request to change the parser behavior so that we can now follow a priority list:
1- Command line arguments
2- Arguments provided in a --config file
3- Arguments provided in the default .py config file provided with openSTL for that method.
4- Default arguments from parser.py.

`https://github.com/chengtan9907/OpenSTL/pull/47`

**Comment by mauriciodev** [comment]
I've been testing it over the past weeks. While the new method is a bit weird to use, it works perfectly. I suggest closing this issue.
