### ISSUE TITLE
Configuration and Running Test Problems 'gcc --version | head -n1'

### ISSUE THREAD

**Issue by netlabcode** [chengtan9907/OpenSTL#59]
When I try to follow the setup and run the test on a Windows 10 PC with GPU.
I have this issue:
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'gcc --version | head -n1' returned non-zero exit status 255.

Is there any problem with the configuration?

**Comment by netlabcode** [comment]
It seems the problem happened because of Windows OS. I tried it on Ubuntu OS, and it can resolve the problem. However, is there any version/part of of OpenSTL or guide that can help to run it on Windows ?

**Comment by Lupin1998** [comment]
Hi, @netlabcode, thanks for your question and comment. Unfortunately, we don't have tested OpenSTL on Windows OS since we don't have an experimental platform on Windows OS. To my knowledge, errors encountered with `gcc` might be related to PyTorch or other required packages with GCC compiling. I suggest you use Ubuntu or try to debug the errors that occurred on Windows OS according to advice online. Sorry for not being able to provide more help.

**Comment by netlabcode** [comment]
Thanks for the answer @Lupin1998 . I managed to solve the issue and make the code work on Windows just by disabling the GCC checking procedure.

**Comment by gqqarno** [comment]
Hi, How to disable GCC checking?

**Comment by gqqarno** [comment]
> Thanks for the answer @Lupin1998 . I managed to solve the issue and make the code work on Windows just by disabling the GCC checking procedure.

Hi, How to disable GCC checking?
