### ISSUE TITLE
checkpoint怎么重新接续训练

### ISSUE THREAD

**Issue by gqqarno** [chengtan9907/OpenSTL#83]
你好，请问怎么接续训练呢

**Comment by Lupin1998** [comment]
Hi, sorry for the late reply. You can resume training by `--auto_resume` or  `--resume_from [PATH_TO_CKPT]`.

**Comment by gqqarno** [comment]
Thank you for your reply. There is another question, where is the file for continuing the training? I can't find it. Thank you very much

**Comment by nauyiahc** [comment]
"Deprecated since version v1.5: resume_from_checkpoint is deprecated in v1.5 and will be removed in v2.0. Please pass the path to Trainer.fit(..., ckpt_path=...) instead."
https://lightning.ai/docs/pytorch/1.9.5/api/pytorch_lightning.trainer.trainer.Trainer.html#pytorch_lightning.trainer.trainer.Trainer

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.

**Comment by easewkx** [comment]
> “自 v1.5 版本起已弃用：resume_from_checkpoint 在 v1.5 中已弃用，将在 v2.0 中删除。请将路径传递给 Trainer.fit（...， ckpt_path=...）。 https://lightning.ai/docs/pytorch/1.9.5/api/pytorch_lightning.trainer.trainer.Trainer.html#pytorch_lightning.trainer.trainer.Trainer

请问是在代码里
![image](https://github.com/chengtan9907/OpenSTL/assets/104662881/4294a493-fb01-4cec-99e7-8ea8a7ef908c)
加上ckpt_path=...然后直接按之前训练的指令开始吗
